USE [master]
GO

/****** Object:  Database [DBIncidencias_crimenes_LA]    Script Date: 11/06/2024 07:56:57 p. m. ******/
CREATE DATABASE [DBIncidencias_crimenes_LA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBIncidencias_crímenes_LA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBIncidencias_crímenes_LA.mdf' , SIZE = 1646592KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBIncidencias_crímenes_LA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBIncidencias_crímenes_LA_log.ldf' , SIZE = 860160KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBIncidencias_crimenes_LA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET RECOVERY FULL 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET  MULTI_USER 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBIncidencias_crimenes_LA] SET  READ_WRITE 
GO

